default_agent: ambient_agent
agents:
  ambient_agent:
    name: ambient_agent
    entrypoint: /Users/madhurpt/Desktop/ambient_agent/ambient_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/madhurpt/Desktop/ambient_agent
    aws:
      execution_role: arn:aws:iam::218208277580:role/agentcore-agentcore_strands-role
      execution_role_auto_create: true
      account: '218208277580'
      region: us-west-2
      ecr_repository: 218208277580.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-ambient_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ambient_agent-izQRtrADde
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:218208277580:runtime/ambient_agent-izQRtrADde
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ambient_agent-builder
      execution_role: arn:aws:iam::218208277580:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-51820286cd
      source_bucket: bedrock-agentcore-codebuild-sources-218208277580-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_JY9hA8MSB/.well-known/openid-configuration
        allowedClients:
        - us65bl9tcmaghof9g6e5pfmui
    request_header_configuration: null
    oauth_configuration: null
